version: '3.7'

services:
  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_ENV: production
      SUPERSET_LOAD_EXAMPLES: "yes"
      SUPERSET_SECRET_KEY: "rasme"
    volumes:
      - superset_home:/app/superset_home
    restart: always
    command: >
      bash -c "
        superset db upgrade &&
        superset fab create-admin \
          --username admin \
          --firstname Superset \
          --lastname Admin \
          --email admin@superset.com \
          --password admin &&
        superset load_examples &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088
      "

volumes:
  superset_home:
